blog/urls.py
from django.conf.urls import url
from . import views
from .views import Home


urlpatterns = [
    url(r'^$', Home.as_view(), name="all_posts"),
    url(r'^(?P<post_id>[0-9]+)/$', views.single_post, name='blog_single_post'),
    url(r'^category/(?P<cat_id>[0-9]+)/$', views.cat_posts, name='blog_cat_post'),
]

testsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from testsite import settings
from blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r'^$', views.home, name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
from django.db import models
from testsite.baseModel import BaseModel
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import MPTTModel, TreeForeignKey
from django.utils.crypto import get_random_string


def set_image_name(instance, filename):
    name = get_random_string(40)
    ext = filename.split('.')[-1]
    path = 'images/{}.{}'.format(name, ext)
    return path


class Category(MPTTModel, BaseModel):
    category_title = models.CharField(max_length=255, verbose_name="Категория")
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    category_image = models.ImageField(blank=True, default="", upload_to=set_image_name)
    category_description = RichTextUploadingField(verbose_name="Описание категории", blank=True, default="")

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    class MPTTMeta:
        order_insertion_by = ['category_title']

    def __str__(self):
        return "{}".format(self.category_title)

    def show_image(self):
        """ Показывает превью изображения в админке """
        if self.category_image:
            return '<img src="{}" width=40>'.format(self.category_image.url)
        else:
            return "--"

    def get_count_posts(self):
        """ Получает количество постов """
        count = Post.objects.filter(post_category=self.id).count()
        return count

    show_image.allow_tags = True
    get_count_posts.short_description = "Кол-во постов"


class Post(BaseModel):
    post_title = models.CharField(max_length=255, verbose_name="Заголовок")
    post_category = TreeForeignKey(Category, blank=True)
    post_description = models.CharField(max_length=170, blank=True, verbose_name="META DESC", default="")
    post_text = RichTextUploadingField(verbose_name="Текст поста", blank=True, default="")
    post_image = models.ImageField(blank=True, default='', upload_to=set_image_name, verbose_name="Главное изображение")
    post_active = models.BooleanField(default=True, verbose_name="Вкл/Выкл")

    def __str__(self):
        return "{}".format(self.post_title)

    def show_image(self):
        """ Показывает превью главного изображения в админке """
        if self.post_image:
            return '<img src="{}" width=40>'.format(self.post_image.url)
        else:
            return "--"

    def get_count_comments(self):
        """ Получает количество комментарив поста """
        count = Comment.objects.filter(comment_parent=self.id).count()
        return count

    show_image.allow_tags = True
    show_image.short_description = "Главное изображение"
    get_count_comments.short_description = "Кол-во комментариев"

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"


class Comment(BaseModel):
    comment_parent = models.ForeignKey(Post, related_name="comment_parent", verbose_name="Пост коментария")
    comment_text = models.TextField()

    def __str__(self):
        return "Комментарий записи - {}".format(self.comment_parent.post_title)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

blog/forms.py
from django import forms
from django.forms import HiddenInput, Textarea
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text", "comment_parent"]
        widgets = {
            'comment_parent': HiddenInput(),
            'comment_text': Textarea(attrs={'class': 'form-control', 'rows': '5', 'cols': ''})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post
from .forms import CommentForm
from testsite import settings
from django.views import View


def home(request):
    context = {"name": "Django", "theme": settings.SITE_THEME}
    return render(request, settings.SITE_THEME + '/base.html', context)


def all_posts(request):
    posts = Post.objects.all().order_by("-created")
    return render(request, settings.SITE_THEME + '/blog/blog_base.html', {"posts": posts})


def cat_posts(request, cat_id):
    posts = Post.objects.filter(post_category=cat_id).order_by("-created")
    return render(request, settings.SITE_THEME + '/blog/blog_base.html', {"posts": posts})


def single_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(initial={'comment_parent': post_id})
    context = {'post': post, 'form': form}
    if request.POST:
        f = CommentForm(request.POST)
        f.save()
    return render(request, settings.SITE_THEME + '/blog/single_post.html', context)


class Home(View):

    def get(self, request):
        context = {"name": "Django"}
        return render(request, settings.SITE_THEME + '/base.html', context)

blog/templates/first/blog/blog_base.html
{% extends 'first/base.html' %}

{% block title %} List all posts {% endblock title %}

{% block content %}
    <div class="blog">
        <div class="container">
            {% for post in posts %}
                <div class="row">
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="col-sm-3">
                                {% if post.post_image %}
                                    <img src="{{ MEDIA_URL }}{{ post.post_image }}" alt="{{ post.post_title }}" class="img-responsive img-thumbnail">
                                {% else %}
                                    <img src="//placehold.it/300x230" class="img-responsive img-thumbnail">
                                {% endif %}
                            </div>
                            <div class="col-sm-9">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h2 class="pull-left" style="margin-top: 0;">{{ post.post_title }}</h2>
                                        <span class="badge pull-right">{{ post.comment_parent.all | length }}</span>
                                        <span class="badge pull-right">{{ post.post_category }}</span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        {% autoescape off %}
                                            {{ post.post_text | truncatewords_html:40 }}
                                        {% endautoescape %}
                                    </div>
                                </div>
                                <div class="row">
                                        <div class="col-sm-12">
                                            <div>
                                                <a href="{% url 'blog_single_post' post.id %}" class="btn btn-primary btn-sm">Read more</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
                <hr>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

blog/templates/first/blog/single_post.html
{% extends 'first/base.html' %}

{% block title %} {{ post.post_title }} {% endblock title %}

{% block content %}
    <div class="blog">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1 class="text-center">{{ post.post_title }}</h1>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-4">Category: <span class="badge">{{ post.post_category }}</span></div>
                <div class="col-sm-4 text-center">Created: <span class="badge">{{ post.created }}</span></div>
                <div class="col-sm-4 text-right">Comments: <span class="badge">{{ post.comment_parent.all | length }}</span></div>
            </div>
            <hr>
            <div class="row">
                <div class="col-sm-12">
                    <div style="text-align: justify;">
                        {% autoescape off %}
                            {% if post.post_image %}
                                    <img class="img-responsive img-thumbnail" style="max-width: 400px; float: left; margin-right: 20px; margin-bottom: 10px;" src="{{ MEDIA_URL }}{{ post.post_image }}" alt="{{ post.post_title }}">
                                {% endif %}
                            {{ post.post_text }}
                        {% endautoescape %}
                    </div>
                </div>
            </div>
            <h3 class="text-center">Comments for {{ post.post_title }}</h3>
            {% if user.username %}
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <form class="form" action="" method="post">
                            {% csrf_token %}
                            {{ form.comment_parent }}
                            <div class="form-group">
                                <label for="id_comment_text">Comment text</label>
                                {{ form.comment_text.errors }}
                                {{ form.comment_text }}
                            </div>
                            <button class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
                <hr>
                {% else %}
                <p class="text-info text-center">Войдите что-бы иметь возможность оставить комментарий!</p>
            {% endif %}
            {% if post.comment_parent.all %}
                {% for comment in post.comment_parent.all %}
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    Comment #{{ comment.id }} by Username
                                    <span class="text-default pull-right">{{ comment.created }}</span>
                                </div>
                                <div class="panel-body">{{ comment.comment_text }}</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock content %}